/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface WorkgridAction {
    /**
    * The label
    */
    'label': string;
  }
}

declare namespace LocalJSX {
  interface MyComponent extends JSXBase.HTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface WorkgridAction extends JSXBase.HTMLAttributes {
    /**
    * The label
    */
    'label'?: string;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'workgrid-action': WorkgridAction;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {



  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLWorkgridActionElement extends Components.WorkgridAction, HTMLStencilElement {}
  var HTMLWorkgridActionElement: {
    prototype: HTMLWorkgridActionElement;
    new (): HTMLWorkgridActionElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'workgrid-action': HTMLWorkgridActionElement;
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

