/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface SnAction {
    'label': string;
    'type': string;
  }
  interface SnImage {
    'alt': string;
    'src': string;
  }
  interface SnInfoHeader {
    'sentAt': string;
    'sourceImage': string;
    'sourceName': string;
  }
  interface SnNotification {}
  interface SnTextBlock {}
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLSnActionElement extends Components.SnAction, HTMLStencilElement {}
  var HTMLSnActionElement: {
    prototype: HTMLSnActionElement;
    new (): HTMLSnActionElement;
  };

  interface HTMLSnImageElement extends Components.SnImage, HTMLStencilElement {}
  var HTMLSnImageElement: {
    prototype: HTMLSnImageElement;
    new (): HTMLSnImageElement;
  };

  interface HTMLSnInfoHeaderElement extends Components.SnInfoHeader, HTMLStencilElement {}
  var HTMLSnInfoHeaderElement: {
    prototype: HTMLSnInfoHeaderElement;
    new (): HTMLSnInfoHeaderElement;
  };

  interface HTMLSnNotificationElement extends Components.SnNotification, HTMLStencilElement {}
  var HTMLSnNotificationElement: {
    prototype: HTMLSnNotificationElement;
    new (): HTMLSnNotificationElement;
  };

  interface HTMLSnTextBlockElement extends Components.SnTextBlock, HTMLStencilElement {}
  var HTMLSnTextBlockElement: {
    prototype: HTMLSnTextBlockElement;
    new (): HTMLSnTextBlockElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'sn-action': HTMLSnActionElement;
    'sn-image': HTMLSnImageElement;
    'sn-info-header': HTMLSnInfoHeaderElement;
    'sn-notification': HTMLSnNotificationElement;
    'sn-text-block': HTMLSnTextBlockElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface SnAction extends JSXBase.HTMLAttributes<HTMLSnActionElement> {
    'label'?: string;
    'type'?: string;
  }
  interface SnImage extends JSXBase.HTMLAttributes<HTMLSnImageElement> {
    'alt'?: string;
    'src'?: string;
  }
  interface SnInfoHeader extends JSXBase.HTMLAttributes<HTMLSnInfoHeaderElement> {
    'sentAt'?: string;
    'sourceImage'?: string;
    'sourceName'?: string;
  }
  interface SnNotification extends JSXBase.HTMLAttributes<HTMLSnNotificationElement> {}
  interface SnTextBlock extends JSXBase.HTMLAttributes<HTMLSnTextBlockElement> {}

  interface IntrinsicElements {
    'my-component': MyComponent;
    'sn-action': SnAction;
    'sn-image': SnImage;
    'sn-info-header': SnInfoHeader;
    'sn-notification': SnNotification;
    'sn-text-block': SnTextBlock;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


